---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
data("instacart")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A
Number of items ordered in each aisle
```{r}
instacart %>% 
  group_by(aisle) %>% 
  summarize(n = n()) %>% 
  filter(n >10000) %>% 
  mutate(aisle = forcats::fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B
The Organic Whole Strawberries' order hour of day in different days 
```{r}
instacart %>% 
  filter(product_name == "Organic Whole Strawberries" ) %>% 
  mutate(
    order_dow=recode(order_dow,
                     `0`="Sunday",`1`="Monday",`2`="Tuesday",`3`="Wednesday",
                     `4`="Thursday",`5`="Friday",`6`="Saturday"),
    order_dow = factor(order_dow,order = TRUE, levels = c("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"))
    ) %>% 
  plot_ly(x = ~order_dow, y = ~order_hour_of_day, color = ~product_name, type = "box",
          colors = "Set2")

```

### Chart C
The Comparison of Organic Whole String Cheese and Organic Hass Avocado sold in a week.
```{r}
instacart %>% 
  mutate(
    order_dow=recode(order_dow,
                     `0`="Sunday",`1`="Monday",`2`="Tuesday",`3`="Wednesday",
                     `4`="Thursday",`5`="Friday",`6`="Saturday"),
    order_dow = factor(order_dow,order = TRUE, levels = c("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"))
    ) %>% 
  filter(
    product_name == "Organic Whole String Cheese" | 
      product_name == "Organic Hass Avocado"
  ) %>% 
  group_by(product_name, order_dow) %>% 
  summarize(
    Total_sold_a_day = n()
  ) %>% 
  plot_ly(x = ~order_dow, y = ~Total_sold_a_day, 
          group = ~product_name, color = ~product_name, 
          type = "scatter", mode = "makers") 
```

